#right_format = """$all"""
#command_timeout= 500
#scan_timeout = 30
add_newline = false





format = """$username$hostname$directory
[│$duration](bold #1bd20e)
[└─>\\$](bold #1bd20e)"""
############################
[username]
style_user = "#c50ed2"
style_root = "#70c0b1"
format = "[┌─\\[[$user](bold #c50ed2)](bold #1bd20e)"
disabled = false
show_always = true
############################
[hostname]
ssh_only = false
format =  "[[@](bold #fefefe)[$hostname](bold #fdbc4b)\\]](bold #1bd20e)"
#trim_at = ".companyname.com"
disabled = false
style = "(#1bd20e)"
###########################
[directory]
truncation_length = 5
truncation_symbol = "…/"
style = "bold cyan"
format = "[[─\\[](bold #1bd20e)[$path](bold cyan)\\]](bold #1bd20e)"
#truncate_to_repo = true
#disabled = true
#read_only = "!"
#read_only_style = "(bold red)"
#repo_root_style =
#home_symbol = "U+2302"
#use_os_path_sep = true
##############################



